sudo: false
compiler: clang
env:
  - CC=clang CXX=clang++ npm_config_clang=1 BUILD_ONLY=true GYP_DEFINES="use_obsolete_asm=true"
addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - libssl-dev
    - g++-multilib

branches:
  only:
    - master
    - /^ena-.*$/

before_install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
- source $HOME/.bashrc
- nvm install 6
- npm install
- npm run compile

- if [ $TARGET_ARCH == "ia32" ]; then
    sudo ln -s /usr/include/asm-generic /usr/include/asm;
  fi

install:
- node ci/prepare.js

script:
- node ci/build.js

after_success:
- node ci/deploy.js

os:
- linux
- osx

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1 BUILD_ONLY=true GYP_DEFINES="use_obsolete_asm=true" TARGET_ARCH="ia32"
      sudo: required
